# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Open source game tools
  pt: Ferramentas abertas para criação de jogos
email: https://marcosvital.github.io/
description:
  en: This is a project to organize a list of open source tools that can be used to create computer games.
  pt: Este é um projeto com objetivo de organizar uma lista de ferramentas open source que possam ser usadas na criação de jogos de computador.
index:
  en:
  pt: bem-vindo.html
feed:
  en: /feed.xml
  pt: /feed_pt.xml
baseurl: "/open-game-tools" # the subpath of your site, e.g. /blog
url: "http://marcosvital.github.io" # the base hostname & protocol for your site
twitter_username: marcosvcvital
github_username:  marcosvital

# Build settings
markdown: kramdown
